// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmjblsaajzlwpqibvvzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtamJsc2Fhanpsd3BxaWJ2dnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjI5NDEsImV4cCI6MjA3Mjg5ODk0MX0.n3kc9z0MsqTQCLtn7dti3BiBorKhdu3ltXaCRNj38uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});