// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvjhoitoxmxdhazgfcmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2amhvaXRveG14ZGhhemdmY21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODgwNzQsImV4cCI6MjA3Mzk2NDA3NH0.U50LmtQVtNkai_D6Zhdzb2EGFNKfOw_0tQXylMk4bmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
